"""Block documents to LaTeX, with a line map for SyncTeX.

Every generated line carries a tag ``[section id, block id, field]`` so a
double-click in the PDF can be traced back through SyncTeX (PDF position to
generated line) to the block and field that produced it. The design itself
lives in ``src/common/cvmodern.sty``; this module only writes its macros.
"""
from __future__ import annotations

import datetime as _dt
import math
import re
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple

from . import inline
from .model import DocumentError

Tag = Optional[List[Optional[str]]]

STYLE_INPUT = r"\input{src/common/cvmodern.sty}"
MONTHS = ["January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December"]

# Rough capacity of one line of body text in the content column, used only to
# keep short entries together on one page.
CHARS_PER_LINE = 88


class Emitter:
    """Collects generated lines together with their source tags."""

    def __init__(self) -> None:
        self.lines: List[str] = []
        self.tags: List[Tag] = []

    def add(self, text: str, tag: Tag = None) -> None:
        for line in str(text).split("\n"):
            self.lines.append(line)
            self.tags.append(list(tag) if tag else None)

    def text(self) -> str:
        return "\n".join(self.lines) + "\n"


def today() -> str:
    now = _dt.date.today()
    return "%d %s %d" % (now.day, MONTHS[now.month - 1], now.year)


def _pdf_string(value: str) -> str:
    """Plain text for PDF metadata, with TeX specials escaped."""
    return inline.escape(inline.plain(value)).replace("\n", " ")


def _contacts(header: Dict[str, Any], profile: Dict[str, Any]) -> List[Dict[str, str]]:
    known = (profile or {}).get("contacts") or {}
    out: List[Dict[str, str]] = []
    for item in header.get("contacts") or []:
        if isinstance(item, dict):
            out.append({"icon": str(item.get("icon") or "circle"), "text": str(item.get("text") or ""),
                        "url": str(item.get("url") or "")})
            continue
        entry = known.get(item)
        if not entry:
            raise DocumentError("The header asks for contact %r, which profile.json does not define" % item)
        out.append({"icon": str(entry.get("icon") or "circle"), "text": str(entry.get("text") or ""),
                    "url": str(entry.get("url") or "")})
    return out


def _preamble(em: Emitter, doc: Dict[str, Any], profile: Dict[str, Any], source: str, kind_label: str) -> None:
    name = (doc.get("header") or {}).get("name") or (profile or {}).get("name") or ""
    pdf = doc.get("pdf") or {}
    em.add("% !TeX program = lualatex")
    em.add("%% Generated from %s by scripts/cvkit. Do not edit this file:" % source)
    em.add("% change the JSON document (or use the Runner's block editor) and rebuild.")
    em.add(r"\documentclass[10pt,a4paper]{article}")
    em.add(STYLE_INPUT)
    em.add(r"\hypersetup{")
    em.add("  pdfauthor = {%s}," % _pdf_string(name))
    em.add("  pdftitle = {%s}," % _pdf_string(pdf.get("title") or ("%s - %s" % (name, kind_label))))
    if pdf.get("subject"):
        em.add("  pdfsubject = {%s}," % _pdf_string(pdf["subject"]))
    if pdf.get("keywords"):
        em.add("  pdfkeywords = {%s}," % _pdf_string(pdf["keywords"]))
    em.add("}")


def _header(em: Emitter, doc: Dict[str, Any], profile: Dict[str, Any]) -> None:
    header = doc.get("header") or {}
    name = header.get("name") or (profile or {}).get("name") or ""
    tag = [None, "header", None]
    em.add(r"\cvHeader{%s}{%s}{%s}{%%" % (inline.to_latex(name), inline.facts_to_latex(header.get("headline")),
                                          inline.facts_to_latex(header.get("tagline"))), tag)
    for index, contact in enumerate(_contacts(header, profile)):
        em.add(r"\cvContact{%s}{%s}{%s}" % (inline.escape(contact["icon"]), inline.to_latex(contact["text"]),
                                           inline._escape_url(contact["url"])),
               [None, "header", "contacts.%d" % index])
    em.add("}", tag)


def estimate_lines(block: Dict[str, Any]) -> int:
    """Lines an entry occupies, so that it is not split without need."""
    lines = 1
    if block.get("meta"):
        lines += 1
    if block.get("text"):
        lines += math.ceil(len(inline.plain(block["text"])) / CHARS_PER_LINE)
    for item in block.get("items") or []:
        lines += max(1, math.ceil(len(inline.plain(item)) / (CHARS_PER_LINE - 3)))
    return min(lines + 1, 16)


def block_height(block: Optional[Dict[str, Any]]) -> int:
    """Estimated height in lines of any block, for keeping titles with content."""
    if not block:
        return 2
    kind = block.get("type")
    if kind == "entry":
        return estimate_lines(block)
    if kind == "summary":
        return 2 + math.ceil(len(inline.plain(block.get("text"))) / (CHARS_PER_LINE + 8))
    if kind == "cards":
        cards = block.get("cards") or []
        first_row = cards[:2]
        tallest = max([1 + sum(max(1, math.ceil(len(inline.plain(item)) / 44)) for item in card.get("items") or [])
                       for card in first_row] or [2])
        return tallest + 1
    if kind == "rows":
        rows = (block.get("rows") or [])[:3]
        return 1 + sum(max(1, math.ceil(len(inline.plain(row.get("text"))) / CHARS_PER_LINE)) for row in rows)
    if kind == "text":
        return 1 + math.ceil(len(inline.plain(block.get("text"))) / (CHARS_PER_LINE + 12))
    return 2


def _entry(em: Emitter, sid: str, block: Dict[str, Any]) -> None:
    bid = block["id"]
    em.add(r"\begin{cvEntry}[%d]{%s}{%s}{%s}{%s}" % (
        estimate_lines(block), inline.to_latex(block.get("date")), inline.to_latex(block.get("title")),
        inline.facts_to_latex(block.get("org")), inline.facts_to_latex(block.get("meta"))),
        [sid, bid, "title"])
    if block.get("text"):
        em.add(inline.to_latex(block["text"]), [sid, bid, "text"])
    items = [item for item in block.get("items") or [] if str(item).strip()]
    if items:
        em.add(r"\begin{cvItems}", [sid, bid, "items"])
        for index, item in enumerate(items):
            em.add(r"\item " + inline.to_latex(item), [sid, bid, "items.%d" % index])
        em.add(r"\end{cvItems}", [sid, bid, "items"])
    em.add(r"\end{cvEntry}", [sid, bid, None])


def _card(card: Dict[str, Any]) -> str:
    items = "".join(r"\cvCardItem{%s}" % inline.to_latex(item) for item in card.get("items") or [] if str(item).strip())
    return r"\cvCard{%s}{%s}" % (inline.to_latex(card.get("title")), items)


def _cards(em: Emitter, sid: str, block: Dict[str, Any]) -> None:
    bid = block["id"]
    cards = [card for card in block.get("cards") or [] if card.get("title") or card.get("items")]
    for start in range(0, len(cards), 2):
        pair = cards[start:start + 2]
        em.add(r"\cvCardRow", [sid, bid, "cards.%d" % start])
        for offset, card in enumerate(pair):
            em.add("  {%s}" % _card(card), [sid, bid, "cards.%d" % (start + offset)])
        if len(pair) == 1:
            em.add("  {}", [sid, bid, None])


def _block(em: Emitter, sid: str, block: Dict[str, Any]) -> None:
    kind, bid = block["type"], block["id"]
    em.add("% @block " + bid, [sid, bid, None])
    if kind == "summary":
        em.add(r"\cvSummary{%s}" % inline.to_latex(block.get("text")), [sid, bid, "text"])
    elif kind == "entry":
        _entry(em, sid, block)
    elif kind == "cards":
        _cards(em, sid, block)
    elif kind == "rows":
        for index, row in enumerate(block.get("rows") or []):
            if not (row.get("label") or row.get("text")):
                continue
            em.add(r"\cvRow{%s}{%s}" % (inline.to_latex(row.get("label")), inline.facts_to_latex(row.get("text"))),
                   [sid, bid, "rows.%d" % index])
    elif kind == "text":
        em.add(r"\cvText{%s}" % inline.to_latex(block.get("text")), [sid, bid, "text"])
    elif kind == "latex":
        em.add(block.get("latex") or "", [sid, bid, "latex"])
    elif kind == "pagebreak":
        em.add(r"\cvPageBreak", [sid, bid, None])


def render_cv(doc: Dict[str, Any], profile: Dict[str, Any], source: str = "a JSON document") -> Tuple[str, List[Tag]]:
    em = Emitter()
    _preamble(em, doc, profile, source, "Curriculum Vitae")
    em.add(r"\begin{document}")
    name = (doc.get("header") or {}).get("name") or (profile or {}).get("name") or ""
    if doc.get("footer"):
        em.add(r"\cvFooter{%s}{%s}" % (inline.to_latex(name), inline.to_latex(doc["footer"])))
    _header(em, doc, profile)
    for section in doc.get("sections") or []:
        sid = section["id"]
        if section.get("hidden"):
            em.add("% hidden section " + sid)
            continue
        em.add("")
        em.add("% @section " + sid, [sid, None, None])
        if section.get("title"):
            visible = [block for block in section.get("blocks") or [] if not block.get("hidden")]
            reserve = min(3 + block_height(visible[0] if visible else None), 20)
            em.add(r"\cvSection[%d]{%s}" % (reserve, inline.to_latex(section["title"])), [sid, None, "title"])
        for block in section.get("blocks") or []:
            if block.get("hidden"):
                em.add("% hidden block " + block["id"])
                continue
            _block(em, sid, block)
    em.add("")
    em.add(r"\end{document}")
    return em.text(), em.tags


def _date_line(doc: Dict[str, Any]) -> str:
    date = doc.get("date") or today()
    place = doc.get("place") or ""
    return "%s, %s" % (place, date) if place else date


def linked_body(doc: Dict[str, Any], resolver: Optional[Callable[[str], str]]) -> List[Dict[str, Any]]:
    """The letter body, taken from a text field when ``bodyFrom`` is set."""
    link = doc.get("bodyFrom")
    if not link:
        return doc.get("body") or []
    if resolver is None:
        raise DocumentError("This letter takes its body from %s, which cannot be resolved here" % link)
    text = resolver(link)
    paragraphs = [part.strip() for part in re.split(r"\n\s*\n", text or "") if part.strip()]
    return [{"id": "linked-%d" % (index + 1), "type": "paragraph", "text": part}
            for index, part in enumerate(paragraphs)]


def render_letter(doc: Dict[str, Any], profile: Dict[str, Any], source: str = "a JSON document",
                  resolver: Optional[Callable[[str], str]] = None) -> Tuple[str, List[Tag]]:
    em = Emitter()
    _preamble(em, doc, profile, source, "Letter")
    em.add(r"\begin{document}")
    name = (doc.get("header") or {}).get("name") or (profile or {}).get("name") or ""
    em.add(r"\cvFooter{%s}{%s}\thispagestyle{empty}" % (inline.to_latex(name), inline.to_latex(doc.get("subject") or "Letter")))
    _header(em, doc, profile)
    recipient = [line.strip() for line in str(doc.get("recipient") or "").splitlines() if line.strip()]
    em.add(r"\cvLetterAddress{%s}{%s}" % (r"\\".join(inline.to_latex(line) for line in recipient),
                                         inline.to_latex(_date_line(doc))), [None, "address", "recipient"])
    if doc.get("subject"):
        em.add(r"\cvLetterSubject{%s}" % inline.to_latex(doc["subject"]), [None, "address", "subject"])
    em.add(r"\begin{cvLetterBody}")
    if doc.get("salutation"):
        em.add(inline.to_latex(doc["salutation"]), [None, "address", "salutation"])
        em.add("")
    for block in linked_body(doc, resolver):
        if block.get("hidden"):
            em.add("% hidden paragraph " + block["id"])
            continue
        bid = block["id"]
        em.add("% @block " + bid, [None, bid, None])
        if block["type"] == "latex":
            em.add(block.get("latex") or "", [None, bid, "latex"])
        else:
            em.add(inline.to_latex(block.get("text")), [None, bid, "text"])
        em.add("")
    em.add(r"\end{cvLetterBody}")
    em.add(r"\cvLetterClosing{%s}{%s}" % (inline.to_latex(doc.get("closing") or "Sincerely,"),
                                         inline.to_latex(doc.get("signature") or name)), [None, "closing", "closing"])
    if doc.get("enclosures"):
        em.add(r"\cvLetterEnclosures{%s}" % inline.to_latex(doc["enclosures"]), [None, "closing", "enclosures"])
    em.add(r"\end{document}")
    return em.text(), em.tags


def render(doc: Dict[str, Any], profile: Dict[str, Any], source: str = "a JSON document",
           resolver: Optional[Callable[[str], str]] = None) -> Tuple[str, List[Tag]]:
    if doc["kind"] == "cv":
        return render_cv(doc, profile, source)
    if doc["kind"] == "letter":
        return render_letter(doc, profile, source, resolver)
    raise DocumentError("Text documents are exported as Markdown, not typeset")


def locate(tags: Sequence[Tag], line: int) -> Optional[Dict[str, Optional[str]]]:
    """The block behind generated ``line`` (1-based), searching upwards."""
    index = min(max(line, 1), len(tags)) - 1
    for probe in range(index, -1, -1):
        tag = tags[probe] if probe < len(tags) else None
        if tag and (tag[1] or tag[0]):
            return {"section": tag[0], "block": tag[1], "field": tag[2], "line": probe + 1}
    return None


def block_lines(tags: Sequence[Tag], block_id: str) -> Optional[Tuple[int, int]]:
    """First and last generated line (1-based) of a block or section."""
    hits = [index + 1 for index, tag in enumerate(tags) if tag and (tag[1] == block_id or (tag[0] == block_id))]
    return (hits[0], hits[-1]) if hits else None
